name: ci
on: push
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      if: "startsWith(github.ref, 'refs/tags/v')"
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!
    - uses: docker/build-push-action@v2
      if: "startsWith(github.ref, 'refs/tags/v')"
      with:
        push: ${{ endswith(github.ref, 'master') }}
        tags: "ghcr.io/${{ github.repository_owner }}/${{github.repository}}:${GITHUB_REF#refs/tags/v}"
        context: .
        file: ./Dockerfile